# Generated by Django 3.1.2 on 2020-11-10 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoHabitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('fecha_desde', models.CharField(max_length=250)),
                ('fecha_hasta', models.CharField(max_length=250)),
                ('codigo_reserva', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disponible', models.BooleanField()),
                ('cant_huespedes', models.IntegerField()),
                ('cant_habitaciones', models.IntegerField()),
                ('precio_total', models.FloatField()),
                ('cant_dias', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('numero', models.IntegerField()),
                ('disponible', models.BooleanField()),
                ('fecha_checking', models.DateField()),
                ('fecha_checkout', models.DateField()),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelApp1.tipohabitacion')),
            ],
        ),
    ]
