# Generated by Django 3.1.2 on 2020-10-26 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administradores',
            fields=[
                ('nombre', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('dni_admin', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('nombre', models.CharField(max_length=250)),
                ('apellido', models.CharField(max_length=250)),
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('telefono', models.IntegerField()),
                ('usuario', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField(default=100)),
                ('numero', models.IntegerField()),
                ('tipo', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('fecha_desde', models.CharField(max_length=250)),
                ('fecha_hasta', models.DateTimeField()),
                ('codigo_reserva', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(default='activa', max_length=250)),
                ('cant_huespedes', models.IntegerField()),
                ('cant_habitaciones', models.IntegerField(default=1)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
