# Generated by Django 3.1.2 on 2020-10-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoHabitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=40)),
            ],
        ),
    ]
