# Generated by Django 3.1.1 on 2020-11-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='fecha_checking',
            field=models.DateField(verbose_name='%d/%m/%Y'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='fecha_checkout',
            field=models.DateField(verbose_name='%d/%m/%Y'),
        ),
    ]
