# Generated by Django 3.1.1 on 2020-11-20 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fechaxhabitacion',
            old_name='numero_habtiacion',
            new_name='numero_habitacion',
        ),
    ]
