# Generated by Django 3.1.1 on 2020-10-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='cant_dias',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
