# Generated by Django 3.1.2 on 2020-10-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='dni',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
