# Generated by Django 3.1.2 on 2020-10-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp1', '0002_auto_20201028_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='codigo_reserva',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
