# Generated by Django 3.1.1 on 2020-11-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp1', '0002_auto_20201111_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='fecha_checkout',
            field=models.DateField(verbose_name='%d/%m/%Ydsdsdsd'),
        ),
    ]
