# Generated by Django 3.1.1 on 2020-11-04 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp1', '0002_reservas_cant_dias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservas',
            name='Habitacion',
        ),
    ]
