# Generated by Django 3.1.1 on 2020-11-13 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp1', '0003_auto_20201113_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='fecha_checking',
            field=models.DateTimeField(verbose_name=datetime.datetime),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='fecha_checkout',
            field=models.DateField(verbose_name='%d/%m/%Y'),
        ),
    ]
