# Generated by Django 3.1.2 on 2020-10-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp1', '0003_auto_20201014_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='codigo_reserva',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
