# Generated by Django 3.1.1 on 2020-11-21 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp1', '0003_auto_20201120_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fechaxhabitacion',
            old_name='fecha_checking',
            new_name='f_checking',
        ),
        migrations.RenameField(
            model_name='fechaxhabitacion',
            old_name='fecha_checkout',
            new_name='f_checkout',
        ),
    ]
