# Generated by Django 3.1.2 on 2020-10-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp1', '0004_auto_20201014_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administradores',
            name='dni_admin',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
