# Generated by Django 3.1.1 on 2020-11-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp1', '0004_auto_20201113_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='fecha_checking',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='fecha_checkout',
            field=models.DateField(),
        ),
    ]
