# Generated by Django 3.1.1 on 2020-11-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp1', '0004_auto_20201121_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechaxhabitacion',
            name='numero_habitacion',
            field=models.IntegerField(),
        ),
    ]
