# Generated by Django 3.1.1 on 2020-11-17 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp1', '0005_auto_20201116_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservas',
            name='disponible',
        ),
    ]
