# Generated by Django 3.1.2 on 2020-10-16 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp1', '0005_auto_20201014_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoHabitacion',
            fields=[
                ('codigo_tipo', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelApp1.tipohabitacion'),
        ),
    ]
