# Generated by Django 3.1.2 on 2020-10-16 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp1', '0006_auto_20201016_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitacion',
            old_name='tipo',
            new_name='cod_tipo_habitacion',
        ),
    ]
