# Generated by Django 3.1.2 on 2020-10-16 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp1', '0007_auto_20201016_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='cod_tipo_habitacion',
        ),
    ]
