# Generated by Django 3.1.2 on 2020-10-16 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp1', '0008_remove_habitacion_cod_tipo_habitacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='cod_tipo_habitacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hotelApp1.tipohabitacion'),
        ),
    ]
