# Generated by Django 3.1.2 on 2020-10-16 19:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp1', '0009_habitacion_cod_tipo_habitacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='cod_tipo_habitacion',
        ),
        migrations.AddField(
            model_name='habitacion',
            name='tipo',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservas',
            name='dni_cliente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hotelApp1.clientes'),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='numero_habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelApp1.habitacion'),
        ),
        migrations.DeleteModel(
            name='tipoHabitacion',
        ),
    ]
