# Generated by Django 3.1.2 on 2020-10-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp1', '0010_auto_20201016_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='cant_huespedes',
            field=models.IntegerField(default=1),
        ),
    ]
