# Generated by Django 3.1.2 on 2020-10-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp1', '0011_reservas_cant_huespedes'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='usuario',
            field=models.CharField(default=None, max_length=32),
        ),
    ]
