# Generated by Django 3.1.2 on 2020-10-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp1', '0012_clientes_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='usuario',
            field=models.CharField(max_length=32),
        ),
    ]
