# Generated by Django 3.1.2 on 2020-10-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp1', '0014_habitacion_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservas',
            name='dni_cliente',
        ),
        migrations.AddField(
            model_name='reservas',
            name='usuario',
            field=models.CharField(default='jones', max_length=250),
        ),
    ]
