# Generated by Django 3.1.2 on 2020-10-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp1', '0017_auto_20201023_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='fecha_desde',
            field=models.CharField(max_length=250),
        ),
    ]
