# Generated by Django 3.1.2 on 2020-10-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp1', '0018_auto_20201023_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='cant_huespedes',
            field=models.IntegerField(),
        ),
    ]
