# Generated by Django 3.1.2 on 2020-10-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp1', '0019_auto_20201023_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='cant_habitaciones',
            field=models.IntegerField(default=1),
        ),
    ]
